### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Fleepin** [searayeah/dota-camera-distance#10]
![image](https://user-images.githubusercontent.com/61661258/233739014-875bc2f1-83f3-4759-b9a7-8e588e161ad6.png)

**Comment by searayeah** [comment]
Can you tell me what is your Dota 2 path?
Have you recently reinstalled the game or moved it to different drive?

**Comment by searayeah** [comment]
It seems that you have just installed Dota and then launched the app. After first installation Steam do not instantly update it's files. Restart Steam and everything will work properly.
