### ISSUE TITLE
Can we enable fog_override 1 by using HxD ?

### ISSUE THREAD

**Issue by onlineporno** [searayeah/dota-camera-distance#16]
Or maybe sv_cheats 1? Years ago i used a patch that could do this. Maybe it's not safe but i wanna use it :)
I remembered, it's was named OvPatch , but now it doesn't work

**Comment by searayeah** [comment]
Enabling sv_cheats 1 would be obviously cheating. I'm not the kind of guy that knows any famous Dota 2 cheats (I didn't really know OvPatch until you mentioned it). So I don't really "cheat" and I don't know the structure of the Dota folder or the structure of the client.dll file. Changing camera distance is very widespread (it is known which lines of code to change in client.dll), so it is easy for me to develop this app. If someone finds out how to edit things like you mentioned and it won't be a major cheat, I might add it to the app. At the moment, I'm focused on keeping only the existing functionality: changing the camera distance.
