### ISSUE TITLE
bans from this?

### ISSUE THREAD

**Issue by SPICEG0D** [searayeah/dota-camera-distance#3]
hey i was just wondering how bannable you think this is compared to the old client text file editing method. it being a exe that find the game and launches it. noob here btw

**Comment by searayeah** [comment]
The app doesn't interfere in the Dota process, it simply automates the work you manually do (edit the client.dll and launch the game)
This line of code launches Dota by calling it's URL: `os.startfile("steam://rungameid/570")`, which is equivalent to lauching the game using your desktop icon.
![image](https://user-images.githubusercontent.com/57370975/197567728-d1e4f283-050c-44bd-b864-a770a102d732.png)
