### ISSUE TITLE
Hex value could not be found

### ISSUE THREAD

**Issue by malyarevich** [searayeah/dota-camera-distance#4]
![image](https://user-images.githubusercontent.com/11439876/199844927-70cd0dc9-14ba-4966-8f85-3a1c57446366.png)
Also I cannot find hex value via HxD app, looks like valve changed approach to setting this camera dispance value after last update.

Any ideas how to fix it?

**Comment by searayeah** [comment]
As for now, you should manually search for  00 00 96 44 00 00 E1 44 in HxD.
I will update the app today to do that automatically.

**Comment by Utogako** [comment]
Any update? Btw, thank you so much for this.

**Comment by Utogako** [comment]
> As for now, you should manually search for `00 00 96 44 00 00 E1 44` in HxD. I will update the app today to do that automatically.

I've just change the search value in config. Works like magic!

**Comment by searayeah** [comment]
I uploaded a new version of the app, which you should preferably use, as the old one might edit some wrong numbers in the client.dll file with this new code.

https://github.com/searayeah/dota-camera-distance/releases/download/3.2/dota-camera-distance.exe

**Comment by Utogako** [comment]
> I uploaded a new version of the app, which you should preferably use, as the old one might edit some wrong numbers in the client.dll file with this new hex value.
> 
> https://github.com/searayeah/dota-camera-distance/releases/download/3.2/dota-camera-distance.exe

Will do. Thank you so much. Appreciate it

**Comment by malyarevich** [comment]
Pretty nice, thanks a lot! [searayeah](https://github.com/searayeah) [Utogako](https://github.com/Utogako)

**Comment by malyarevich** [comment]
again valve changes hex value, any ideas?

**Comment by searayeah** [comment]
> again valve changes hex value, any ideas?

Everything works fine for me, the hex value is the same. Make sure you have the latest version of the app installed (I provided the link above) and try again after verifying the integrity of game files.

**Comment by searayeah** [comment]
Hey, any updates? Everything works now?
