### ISSUE TITLE
Exception: Couldn't find the hex value in client.dll file. Valve might have changed it.

### ISSUE THREAD

**Issue by tylerseitz** [searayeah/dota-camera-distance#9]
The latest patch appears to have broken this wonderful tool. I really wish they would just admit that it is ridiculously too close for modern monitors.
![dota-camera-distance-error-20230306](https://user-images.githubusercontent.com/22688995/223323463-8fad1b13-29c8-4e7d-a3d6-a744b21fdc34.png)

**Comment by searayeah** [comment]
Try lauching again, I updated the code.
